-- 4.	Написать триггер, который логирует
-- (записывает все параметры в отдельную таблицу учёта) все удаления поездов,
-- на которых было продано более 300 билетов. В таблицу аудита надо бы записать и число удалённых билетов.

drop table if exists deleted_trains cascade;
create table deleted_trains (
    id int primary key generated by default as identity,
    category train_category not null default 'c1'::train_category,
    header_station int references stations(id) on delete set null,
    booking_count int
);
create or replace function log_train() returns trigger as $$
declare
    delete_t trains%rowtype;
    total_booking_count int;
    current_booking_count int;
begin
    delete_t := old;
    select count(*) into current_booking_count from
        (select t.id from trains t where t.id = delete_t.id) as tid
    inner join carriages on tid = carriages.train
    inner join booking on carriages.id = booking.carriage;
    if total_booking_count > 300 then
        insert into deleted_trains select *, total_booking_count from delete_t;
    end if;
    return delete_t;
end;
$$ language plpgsql;